CREATE OR REPLACE PACKAGE pctClientes  IS
    PROCEDURE ContatosClientes(customer_id IN CUSTOMERS.CUST_ID%TYPE, V_LIST OUT VARCHAR2);
	FUNCTION getNomeCliente(customer_id IN CUSTOMERS.CUST_ID%TYPE) RETURN VARCHAR2;
END pctClientes  ;
    
CREATE OR REPLACE PACKAGE BODY pctClientes IS
BEGIN
    getNomeCliente  (customer_id IN CUSTOMERS.CUST_ID%TYPE) RETURN VARCHAR2 IS
    	V_NOME VARCHAR2(46);
    BEGIN
    	SELECT 
        U.CUST_FIRST_NAME || ' ' || U.CUST_LAST_NAME
        INTO 
        V_NOME
        FROM CUSTOMERS U
        WHERE U.CUST_ID = customer_id;
    
    	RETURN V_NOME;
    EXCEPTION
    	WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NENHUM DADO ENCONTRADO');
    END getNomeCliente;

---
    ContatosClientes (customer_id IN CUSTOMERS.CUST_ID%TYPE, V_LIST OUT VARCHAR2) IS
        V_NOME VARCHAR2(46);
        V_EMAIL CUSTOMERS.CUST_EMAIL%TYPE;
        V_FONE CUSTOMERS.CUST_MAIN_PHONE_NUMBER%TYPE; 
        V_PAIS COUNTRIES.COUNTRY_NAME%TYPE;
    BEGIN
        
        SELECT 
        U.CUST_FIRST_NAME || ' ' || U.CUST_LAST_NAME, U.CUST_EMAIL, U.CUST_MAIN_PHONE_NUMBER, C.COUNTRY_NAME
        INTO 
        V_NOME, 
        V_EMAIL,
        V_FONE, 
        V_PAIS 
        FROM CUSTOMERS U
        INNER JOIN COUNTRIES  C ON U.COUNTRY_ID = C.COUNTRY_ID
        WHERE U.CUST_ID = customer_id;
    
        V_LIST := 'NOME:'|| V_NOME || ', EMAIL:' || V_EMAIL || ', TELEFONE:'|| V_FONE || ', PAIS:'|| V_PAIS; 
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NENHUM DADO ENCONTRADO');
    END ContatosClientes;
END pctClientes;



---

CREATE OR REPLACE PACKAGE FUNCIONARIO AS FUNCTION NOMECOMPLETO (
        V_EMPLOYEE_ID HR.EMPLOYEES.EMPLOYEE_ID %TYPE
    ) RETURN VARCHAR2;
FUNCTION SALARIO (
    V_EMPLOYEE_ID HR.EMPLOYEES.EMPLOYEE_ID %TYPE
) RETURN NUMBER;
PROCEDURE DADOS_FUNCIONARIO_DEPARTAMENTO (
    V_DEPARTMENT_ID HR.EMPLOYEES.DEPARTMENT_ID %TYPE
);
END FUNCIONARIO;
CREATE OR REPLACE PACKAGE BODY FUNCIONARIO AS FUNCTION NOMECOMPLETO (
        V_EMPLOYEE_ID HR.EMPLOYEES.EMPLOYEE_ID %TYPE
    ) RETURN VARCHAR2 IS V_NOME HR.EMPLOYEES.FIRST_NAME %TYPE;
V_SOBRENOME HR.EMPLOYEES.LAST_NAME %TYPE;
BEGIN
SELECT FIRST_NAME,
    LAST_NAME INTO V_NOME,
    V_SOBRENOME
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;
RETURN V_NOME || ' ' || V_SOBRENOME;
END NOMECOMPLETO;
FUNCTION SALARIO (
    V_EMPLOYEE_ID HR.EMPLOYEES.EMPLOYEE_ID %TYPE
) RETURN NUMBER IS V_SALARIO HR.EMPLOYEES.SALARY %TYPE;
BEGIN
SELECT SALARY INTO V_SALARIO
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;
RETURN V_SALARIO;
END SALARIO;
PROCEDURE DADOS_FUNCIONARIO_DEPARTAMENTO (
    V_DEPARTMENT_ID HR.EMPLOYEES.DEPARTMENT_ID %TYPE
) IS V_NOME HR.EMPLOYEES.FIRST_NAME %TYPE;
V_SOBRENOME HR.EMPLOYEES.LAST_NAME %TYPE;
V_DEP_NAME HR.DEPARTMENTS.DEPARTMENT_NAME %TYPE;
CURSOR C_FUNC IS
SELECT E.FIRST_NAME,
    E.LAST_NAME,
    D.DEPARTMENT_NAME
FROM HR.EMPLOYEES E
    JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID = V_DEPARTMENT_ID;
BEGIN OPEN C_FUNC;
LOOP FETCH C_FUNC INTO V_NOME,
V_SOBRENOME,
V_DEP_NAME;
EXIT
WHEN C_FUNC %NOTFOUND;
DBMS_OUTPUT.PUT_LINE(
    'Funcionário: ' || V_NOME || ' ' || V_SOBRENOME || ' | Departamento: ' || V_DEP_NAME
);
END LOOP;
CLOSE C_FUNC;
END DADOS_FUNCIONARIO_DEPARTAMENTO;
END FUNCIONARIO;


---
CREATE OR REPLACE PACKAGE FUNCIONARIO AS
    FUNCTION NOME_COMPLETO_DEP (
        V_DEPARTMENT_ID HR.EMPLOYEES.DEPARTMENT_ID%TYPE
    ) RETURN VARCHAR2;
END FUNCIONARIO;
CREATE OR REPLACE PACKAGE BODY FUNCIONARIO AS

    FUNCTION NOME_COMPLETO_DEP (
        V_DEPARTMENT_ID HR.EMPLOYEES.DEPARTMENT_ID%TYPE
    ) RETURN VARCHAR2 IS
        V_NOME HR.EMPLOYEES.FIRST_NAME%TYPE;
        V_SOBRENOME HR.EMPLOYEES.LAST_NAME%TYPE;
        V_DEP_NAME HR.DEPARTMENTS.DEPARTMENT_NAME%TYPE;
        V_RESULT VARCHAR2(4000);
    BEGIN
        SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
        INTO V_NOME, V_SOBRENOME, V_DEP_NAME
        FROM HR.EMPLOYEES E
        JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        WHERE E.DEPARTMENT_ID = V_DEPARTMENT_ID
        AND ROWNUM = 1;  

        V_RESULT := V_NOME || ' ' || V_SOBRENOME || ' | Departamento: ' || V_DEP_NAME;
        RETURN V_RESULT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 'Nenhum funcionário no departamento ' || V_DEPARTMENT_ID;
    END NOME_COMPLETO_DEP;

END FUNCIONARIO;