CREATE OR REPLACE VIEW V_HR_1 AS
SELECT 
    E.*, 
    J.JOB_TITLE
FROM HR.EMPLOYEES E
INNER JOIN HR.JOBS J 
    ON J.JOB_ID = E.JOB_ID
WHERE E.SALARY BETWEEN 5000 AND 7000
  AND E.COMMISSION_PCT IS NOT NULL;

SELECT * FROM V_HR_1;

-- 
CREATE VIEW V_COUN_REG AS
SELECT C.COUNTRY_NAME , R.REGION_NAME
FROM HR.COUNTRIES C
INNER JOIN HR.REGIONS R ON R.REGION_ID = C.REGION_ID;

--
CREATE VIEW V_DESDEPART_HR AS
SELECT 
    D.DEPARTMENT_NAME, L.CITY,E.FIRST_NAME || ' ' || LAST_NAME NOME_GERENTE ,E.PHONE_NUMBER
FROM HR.DEPARTMENTS D 
INNER JOIN HR.LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
INNER JOIN HR.EMPLOYEES E ON E.EMPLOYEE_ID = D.MANAGER_ID

--
CREATE VIEW V_FUNCIONARIOS AS
SELECT 
   E.FIRST_NAME || ' ' || LAST_NAME NOME , J.JOB_TITLE
FROM HR.EMPLOYEES E
INNER JOIN HR.JOBS J ON E.JOB_ID = J.JOB_ID;

--
CREATE VIEW V_HR_FUNC_HIST AS
SELECT 
    E.FIRST_NAME || ' ' || E.LAST_NAME AS NOME,
    JH.START_DATE,
    JH.END_DATE,
    J.JOB_TITLE
FROM HR.JOB_HISTORY JH
INNER JOIN HR.EMPLOYEES E 
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
INNER JOIN HR.JOBS J 
    ON J.JOB_ID = JH.JOB_ID;


--
CREATE OR REPLACE VIEW V_HR_FUNC_GER AS
SELECT 
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FUNCIONARIO,
    E.SALARY,
    G.FIRST_NAME || ' ' || G.LAST_NAME AS GERENTE
FROM HR.EMPLOYEES E
LEFT JOIN HR.EMPLOYEES G 
    ON E.MANAGER_ID = G.EMPLOYEE_ID;

--
CREATE OR REPLACE VIEW V_HR_FUNC_DEPT_CITY AS
SELECT 
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FUNCIONARIO,
    D.DEPARTMENT_NAME,
    L.CITY
FROM HR.EMPLOYEES E
INNER JOIN HR.DEPARTMENTS D 
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN HR.LOCATIONS L 
    ON D.LOCATION_ID = L.LOCATION_ID;

--
CREATE OR REPLACE VIEW V_HR_FUNC_CIDADES AS
SELECT 
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FUNCIONARIO,
    J.JOB_TITLE,
    E.DEPARTMENT_ID,
    D.DEPARTMENT_NAME
FROM HR.EMPLOYEES E
INNER JOIN HR.JOBS J 
    ON E.JOB_ID = J.JOB_ID
INNER JOIN HR.DEPARTMENTS D 
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN HR.LOCATIONS L 
    ON D.LOCATION_ID = L.LOCATION_ID
WHERE L.CITY IN ('Tokyo', 'Roma', 'Oxford', 'Munich');

--
CREATE OR REPLACE VIEW V_HR_FUNC_GER_COD AS
SELECT 
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FUNCIONARIO,
    E.EMPLOYEE_ID AS NR_FUNCIONARIO,
    G.FIRST_NAME || ' ' || G.LAST_NAME AS GERENTE,
    G.EMPLOYEE_ID AS NR_GERENTE
FROM HR.EMPLOYEES E
LEFT JOIN HR.EMPLOYEES G 
    ON E.MANAGER_ID = G.EMPLOYEE_ID;

--
CREATE OR REPLACE VIEW V_HR_GER_DEPT_LOC AS
SELECT 
    G.FIRST_NAME || ' ' || G.LAST_NAME AS GERENTE,
    D.DEPARTMENT_NAME,
    L.CITY
FROM HR.DEPARTMENTS D
INNER JOIN HR.EMPLOYEES G 
    ON D.MANAGER_ID = G.EMPLOYEE_ID
INNER JOIN HR.LOCATIONS L 
    ON D.LOCATION_ID = L.LOCATION_ID;

--
CREATE OR REPLACE VIEW V_HR_SALARIO_MAIOR AS
SELECT 
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FUNCIONARIO,
    J.JOB_TITLE,
    E.SALARY
FROM HR.EMPLOYEES E
INNER JOIN HR.JOBS J 
    ON E.JOB_ID = J.JOB_ID
WHERE E.SALARY > 3850;

--
CREATE OR REPLACE VIEW V_HR_SALARIO_FORA_FAIXA AS
SELECT 
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FUNCIONARIO,
    E.SALARY
FROM HR.EMPLOYEES E
WHERE E.SALARY NOT BETWEEN 1500 AND 2850;

--
CREATE VIEW FUN_NOTNANCY_V AS
SELECT 
	E.FIRST_NAME || ' ' || E.LAST_NAME NOME,
	J.JOB_TITLE,
	E.HIRE_DATE
FROM HR.EMPLOYEES E
INNER JOIN HR.JOBS J 
	ON J.JOB_ID = E.JOB_ID
WHERE E.DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID FROM HR.EMPLOYEES 
    WHERE FIRST_NAME = 'Nancy'
) AND FIRST_NAME != 'Nancy';

--
CREATE VIEW FUN_SALARY_MAIOR_V AS
SELECT 
    E.EMPLOYEE_ID MATRICULA,
	E.FIRST_NAME || ' ' || E.LAST_NAME NOME
FROM HR.EMPLOYEES E
WHERE E.SALARY > (
    SELECT AVG(SALARY) FROM HR.EMPLOYEES
);

--
CREATE VIEW FUN_SALARY_MAIOR_DEPART_V AS
SELECT 
    E.EMPLOYEE_ID MATRICULA,
	E.FIRST_NAME || ' ' || E.LAST_NAME NOME
FROM HR.EMPLOYEES E
WHERE E.SALARY  > ALL (
    SELECT AVG(SALARY) AS MEDIA_DEP
    FROM HR.EMPLOYEES
    GROUP BY DEPARTMENT_ID
);

--
CREATE VIEW V_HR_SALES_DIF_ELENI AS
SELECT 
    E.EMPLOYEE_ID AS MATRICULA,
    E.FIRST_NAME || ' ' || E.LAST_NAME AS NOME,
    J.JOB_TITLE
FROM HR.EMPLOYEES E
INNER JOIN HR.JOBS J 
    ON E.JOB_ID = J.JOB_ID
INNER JOIN HR.DEPARTMENTS D 
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_NAME = 'Sales'
  AND E.JOB_ID <> (
        SELECT JOB_ID 
        FROM HR.EMPLOYEES
        WHERE FIRST_NAME = 'Eleni'
    );

--
CREATE VIEW V_HR_DEP_T AS
SELECT 
    E.EMPLOYEE_ID AS MATRICULA,
    E.FIRST_NAME || ' ' || E.LAST_NAME AS NOME
FROM HR.EMPLOYEES E
WHERE E.DEPARTMENT_ID IN (
    SELECT DISTINCT DEPARTMENT_ID
    FROM HR.EMPLOYEES
    WHERE UPPER(FIRST_NAME) LIKE '%T%' 
       OR UPPER(LAST_NAME) LIKE '%T%'
);

--
CREATE VIEW V_HR_DEP_T_SEM_T AS
SELECT 
    E.EMPLOYEE_ID AS MATRICULA,
    E.FIRST_NAME || ' ' || E.LAST_NAME AS NOME
FROM HR.EMPLOYEES E
WHERE E.DEPARTMENT_ID IN (
    SELECT DISTINCT DEPARTMENT_ID
    FROM HR.EMPLOYEES
    WHERE UPPER(FIRST_NAME) LIKE '%T%' 
       OR UPPER(LAST_NAME) LIKE '%T%'
)
AND UPPER(E.FIRST_NAME) NOT LIKE '%T%'
AND UPPER(E.LAST_NAME) NOT LIKE '%T%';


--
CREATE VIEW V_HR_SUB_NANCY AS
SELECT 
    E.FIRST_NAME || ' ' || E.LAST_NAME AS NOME,
    J.JOB_TITLE,
    E.SALARY
FROM HR.EMPLOYEES E
INNER JOIN HR.JOBS J 
    ON E.JOB_ID = J.JOB_ID
WHERE E.MANAGER_ID = (
    SELECT EMPLOYEE_ID
    FROM HR.EMPLOYEES
    WHERE FIRST_NAME = 'Nancy'
);


--
CREATE VIEW V_HR_CIDADE_PRES AS
SELECT 
    E.FIRST_NAME || ' ' || E.LAST_NAME AS NOME,
    J.JOB_TITLE,
    D.DEPARTMENT_NAME,
    L.CITY
FROM HR.EMPLOYEES E
INNER JOIN HR.JOBS J 
    ON E.JOB_ID = J.JOB_ID
INNER JOIN HR.DEPARTMENTS D 
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN HR.LOCATIONS L 
    ON D.LOCATION_ID = L.LOCATION_ID
WHERE L.CITY = (
    SELECT L2.CITY
    FROM HR.EMPLOYEES P
    INNER JOIN HR.DEPARTMENTS D2 
        ON P.DEPARTMENT_ID = D2.DEPARTMENT_ID
    INNER JOIN HR.LOCATIONS L2 
        ON D2.LOCATION_ID = L2.LOCATION_ID
    WHERE P.JOB_ID = 'AD_PRES'
);

--
CREATE VIEW V_HR_MEDIA_PROG_GER AS
SELECT 
    E.EMPLOYEE_ID AS MATRICULA,
    E.FIRST_NAME || ' ' || E.LAST_NAME AS NOME,
    E.SALARY
FROM HR.EMPLOYEES E
WHERE E.SALARY > (
    SELECT AVG(SALARY)
    FROM HR.EMPLOYEES
)
AND E.DEPARTMENT_ID IN (
    SELECT DISTINCT DEPARTMENT_ID
    FROM HR.EMPLOYEES E2
    INNER JOIN HR.JOBS J2 
        ON E2.JOB_ID = J2.JOB_ID
    WHERE UPPER(J2.JOB_TITLE) LIKE '%PROGRAMMER%'
       OR UPPER(J2.JOB_TITLE) LIKE '%MANAGER%'
);

--
CREATE OR REPLACE VIEW vw_produto_mais_caro AS
SELECT 
    prod_subcategory,
    MAX(prod_list_price) AS preco_mais_caro
FROM products
GROUP BY prod_subcategory;

--
CREATE OR REPLACE VIEW vw_clientes_acima_media_1998 AS
SELECT 
    c.cust_first_name || ' ' || c.cust_last_name AS cliente,
    AVG(s.amount_sold) AS media_compras
FROM customers c
JOIN sales s ON c.cust_id = s.cust_id
WHERE s.time_id BETWEEN DATE '1998-01-01' AND DATE '1998-12-31'
GROUP BY c.cust_first_name, c.cust_last_name
HAVING AVG(s.amount_sold) > (
    SELECT AVG(amount_sold)
    FROM sales
    WHERE time_id BETWEEN DATE '1998-01-01' AND DATE '1998-12-31'
);

--
CREATE OR REPLACE VIEW vw_func_sal_total AS
SELECT 
    e.ename AS funcionario,
    e.job AS funcao,
    d.dname AS departamento,
    NVL(e.sal,0) + NVL(e.comm,0) AS "Salário total"
FROM emp e
JOIN dept d ON e.deptno = d.deptno
WHERE d.loc IN ('DALLAS', 'CHICAGO');

--
CREATE OR REPLACE VIEW vw_func_salario_hr AS
SELECT 
    first_name || ' ' || last_name AS "Funcionário",
    salary AS "Salário Mensal"
FROM employees
WHERE salary > 1500
  AND department_id IN (10, 30);

--
CREATE OR REPLACE VIEW vw_sem_gerente AS
SELECT 
    first_name || ' ' || last_name AS funcionario,
    job_id AS funcao
FROM employees
WHERE manager_id IS NULL;

--
CREATE OR REPLACE VIEW vw_func_comissao AS
SELECT 
    first_name || ' ' || last_name AS funcionario,
    salary,
    NVL2(commission_pct, TO_CHAR(commission_pct), 'não comissionado') AS comissao
FROM employees;


--
CREATE OR REPLACE VIEW vw_func_ss AS
SELECT 
    first_name || ' ' || last_name AS funcionario
FROM employees
WHERE (UPPER(first_name || last_name) LIKE '%SS%' AND department_id = 30)
   OR manager_id = 103;

--
CREATE OR REPLACE VIEW vw_func_program_marketing AS
SELECT 
    first_name || ' ' || last_name AS funcionario,
    job_id AS funcao,
    salary
FROM employees
WHERE job_id IN ('IT_PROG', 'MK_MAN', 'MK_REP')
  AND salary NOT IN (1000, 3000, 5000);

--
CREATE OR REPLACE VIEW vw_salario_departamentos AS
SELECT 
    d.department_name,
    SUM(e.salary) AS soma_salarios
FROM employees e
JOIN departments d ON e.department_id = d.department_id
GROUP BY d.department_name
HAVING SUM(e.salary) > 5000;

--
CREATE OR REPLACE VIEW vw_maior_salario_funcao AS
SELECT 
    j.job_title,
    MAX(e.salary) AS "Mais alto por função"
FROM employees e
JOIN jobs j ON e.job_id = j.job_id
GROUP BY j.job_title
HAVING MAX(e.salary) <= 10000;


--
CREATE OR REPLACE VIEW vw_media_salario_manager AS
SELECT 
    j.job_title,
    AVG(e.salary) AS "Média de salário por função"
FROM employees e
JOIN jobs j ON e.job_id = j.job_id
WHERE j.job_title LIKE '%Manager%'
GROUP BY j.job_title;

--
CREATE OR REPLACE VIEW vw_media_salario_manager_filtro AS
SELECT *
FROM vw_media_salario_manager
WHERE "Média de salário por função" BETWEEN 10500 AND 12500;

--
CREATE OR REPLACE VIEW vw_dept_mais_gerentes AS
SELECT 
    d.department_name,
    COUNT(*) AS qtd_gerentes
FROM employees e
JOIN departments d ON e.department_id = d.department_id
JOIN jobs j ON e.job_id = j.job_id
WHERE j.job_title LIKE '%Manager%'
GROUP BY d.department_name
HAVING COUNT(*) > 1;

