--1)
select e.FIRST_NAME || ' ' || e.LAST_NAME as nome, d.DEPARTMENT_NAME,
e1.FIRST_NAME || ' ' || e1.LAST_NAME as gerente
from hr.EMPLOYEES e
inner join hr.DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT join hr.EMPLOYEES e1 on e1.MANAGER_ID = d.MANAGER_ID;

--2)
select e.FIRST_NAME || ' ' || e.LAST_NAME as nome, j.JOB_TITLE,
e.SALARY
from hr.EMPLOYEES e
inner join hr.JOBS j on j.JOB_ID = e.JOB_ID;

--3)
select
 e.FIRST_NAME || ' ' || e.LAST_NAME as nome,d.DEPARTMENT_NAME, j.CITY
from hr.EMPLOYEES e
inner join hr.DEPARTMENTS d on d.DEPARTMENT_ID = e.DEPARTMENT_ID
inner join hr.LOCATIONS j on d.LOCATION_ID = j.LOCATION_ID and city ='Toronto';

--4)
 SELECT
 e.FIRST_NAME || ' ' || e.LAST_NAME as NOME,
 c.COUNTRY_NAME
FROM HR.EMPLOYEES e
INNER JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
INNER JOIN HR.LOCATIONS l ON l.LOCATION_ID = d.LOCATION_ID
INNER JOIN HR.COUNTRIES c ON c.COUNTRY_ID = l.COUNTRY_ID;


--5)
 SELECT
 e.FIRST_NAME || ' ' || e.LAST_NAME as NOME,
 d.FIRST_NAME || ' ' || d.LAST_NAME as gerente
FROM HR.EMPLOYEES e
LEFT JOIN HR.EMPLOYEES d ON d.MANAGER_ID = e.MANAGER_ID;

--6)
 SELECT
 e.FIRST_NAME || ' ' || e.LAST_NAME as NOME,
 j.JOB_TITLE as trabA,
 d.JOB_TITLE as hist,
 h.START_DATE,
 h.END_DATE
FROM HR.EMPLOYEES e
INNER JOIN HR.JOBS j ON j.JOB_ID = e.JOB_ID
left JOIN HR.JOB_HISTORY h ON h.EMPLOYEE_ID = e.EMPLOYEE_ID
RIGHT  JOIN HR.JOBS d ON h.JOB_ID = d.JOB_ID;

--7)
select count(distinct e.EMPLOYEE_ID), d.DEPARTMENT_NAME
from hr.EMPLOYEES e
inner join hr.DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID
group by d.DEPARTMENT_NAME;

--8)
SELECT
 e.FIRST_NAME || ' ' || e.LAST_NAME as NOME,
 c.COUNTRY_NAME
FROM HR.EMPLOYEES e
INNER JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
INNER JOIN HR.LOCATIONS l ON l.LOCATION_ID = d.LOCATION_ID
INNER JOIN HR.COUNTRIES c ON c.COUNTRY_ID = l.COUNTRY_ID
where c.COUNTRY_NAME like '%United States%';


--9)
select e.FIRST_NAME || ' ' || e.LAST_NAME as nome,
d.DEPARTMENT_NAME
from hr.EMPLOYEES e
inner join hr.DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID
left join hr.EMPLOYEES a on d.DEPARTMENT_ID = a.DEPARTMENT_ID
where a.FIRST_NAME like '%lex%';

/*Lista dois */

--1)
SELECT e.EMPLOYEE_ID, e.FIRST_NAME || ' ' || e.last_name as nome,
l.FIRST_NAME || ' ' || l.last_name as nomeGerente
FROM HR.EMPLOYEES e
left join HR.EMPLOYEES l on
e.MANAGER_ID =  l.EMPLOYEE_ID;


--2)
SELECT D.DEPARTMENT_NAME, SUM(L.EMPLOYEE_ID)
FROM HR.DEPARTMENTS D
left join HR.EMPLOYEES l on
D.DEPARTMENT_ID =  l.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

--3)
SELECT e.FIRST_NAME || ' ' || e.last_name as nome
,
l.JOB_ID
FROM HR.EMPLOYEES E
left join HR.JOB_HISTORY l on
E.EMPLOYEE_ID =  l.EMPLOYEE_ID;

--4)

SELECT
L.LOCATION_ID, C.COUNTRY_NAME
FROM HR.COUNTRIES C
LEFT JOIN HR.LOCATIONS L ON
L.COUNTRY_ID = C.COUNTRY_ID;

--5)SELECT E.FIRST_NAME || ' ' || E.last_name as nome
, D.DEPARTMENT_ID
FROM HR.DEPARTMENTS D
RIGHT JOIN HR.JOB_HISTORY H
ON H.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN HR.EMPLOYEES E ON
H.EMPLOYEE_ID = E.EMPLOYEE_ID;


